### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by claranceliberi** [claranceliberi/luckyscore#2]
# Tasks

- [x] lineups (@didiermun )
- [x] season, team and players creation (@hirwablessing )
- [x] assigning player to match, and making fixtures (liberi)
- [x] betting (@jacques-twizeyimana and verite)
